config/routes.rb
Rails.application.routes.draw do
  resources :document_academics
  resources :academics
  resources :clinicals
  get 'document_family/index'
  mount Judge::Engine => '/judge'
  # ActiveAdmin.routes(self)
  # devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  namespace :dynamic_selectable do
    get 'departments/:department_id/functions', to: 'department_functions#index', as: :department_functions
    get 'directions/:direction_id/departments', to: 'direction_departments#index', as: :direction_departments
    get 'general_directions/:general_direction_id/directions', to: 'general_direction_directions#index', as: :general_direction_directions
  end


  resources :general_directions
  resources :functions
  resources :departments
  resources :directions
  resources :labors

  get '/unexpired_contracts' => 'labors#unexpired_contracts'
  get '/full_age' => 'family_groups#full_age'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, path: '/', only: [:sessions]
  devise_scope :user do
  	get "login", to: "devise/sessions#new"

    authenticated :user, lambda {|u| u.role == "admin"} do
      root to: "home#index", as: :authenticated_root
    end

    authenticated :user, lambda {|u| u.role == "none"} do
      root to: "home#index"
    end

    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_root
    end
  end


	get 'home/index'

	resources :family_groups do
    member do
      get 'download'
    end
  end


	resources :employees do
		member do
  		post "pdf"
      get 'download'
  	end
	end

  resources :home do
    member do
      post "listpdf"
    end
  end

end

app/models/employee.rb
require 'carrierwave/orm/activerecord'
class Employee < ApplicationRecord

	has_many :family_groups
	has_many :labors
	has_many :addresses
	has_one :city, through: :addresses
	has_many :academics
	has_one :clinical
	has_many :attachment_files, :as => :imageable
	accepts_nested_attributes_for :attachment_files,  allow_destroy: true
	accepts_nested_attributes_for :addresses, allow_destroy: true

	# attr_accessor :lock_version
	# attr_accessor :original_updated_at

	has_paper_trail :on => [:create, :update, :destroy], :ignore => [:update_at, :created_at]
	accepts_nested_attributes_for :family_groups, allow_destroy: true
	mount_uploader :avatar, ImageUploader
    mount_uploader :copy_document, CopyDocumentUploader
	 

	validates :legajo, :name, :last_name,:document_number,  presence:  { message: "Campo obligatorio" }
	validates :legajo,  numericality: {  message: "	Se permite solo numeros enteros"}
	validates :legajo, length: { is: 5, :message => "Debe tener 5 digitos"}
	validates :name, :last_name, format: { with: /[a-zA-Z]+/, message: "se permiten solo letras" }
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "formato email@email.com"  }, :allow_blank => true
	

	# validate :handle_conflict, on: :update
	extend Enumerize
	enumerize :document_type, in:[:'DNI', :'CI', :'LC', :'LE'], default: :'DNI'	
	enumerize :marital_state, in:[:'SOLTERO/A', :'CONCUBINO/A', :'CASADO/A', :'DIVORCIADO/A', :'VIUDO/A'], default: :'SOLTERO/A'
	enumerize :nationality, in:[:'Argentina', :'Paraguay', :'Brasil', :'Uruguay'], default: :'Argentina'
 



	#aasm colunm: "lock_version" do
	#	lock_version :locked, initial:true
	#	lock_version :unlocked
		#
	#	event :unlock do
	#		transitions from: :locked, to: :unlocked 
	#	end
	#	event :lock do
	#		transitions from: :unlocked, to: :locked 
	#	end
	#end




#   def original_updated_at
#   	@original_updated_at || updated_at.to_f 
#   end
#   attr_writer :original_updated_at

#   def handle_conflict
#   	if @conflict || updated_at.to_f > original_updated_at.to_f
#   		@conflict = true
#   		@original_updated_at = nil
#   		errors.add :base, "Hay cambios que han sido editados"
#   		changes.each do |attribute, values|
#   			errors.add attribute, "was #{values.first}"
#   		end
#   	end
# end


  # def update_with_conflict_validation(*args)
  # 		update_attributes(*args)
  # 		rescue ActiveRecord::StaleObjectError
  # 			 self.lock_version = lock_version_was
  #   		errors.add :base, "Se detecto que otro usuario esta editando este Empleado, por favor salga de la edicion del empleado actual y vuelva a ingresar en minutos." 
	 #    		changes.except("update_at").each do |name, values|
	 #    			errors.add name, "was #{values.first}";
	 #    		end
  #   	false
  # end
  # def legajo_validate?
  # 	Employee.exists?(:legajo => "David")
  # end
  # def document_number_validate?
  # 	@employee.valid?
  # end
  


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_normal!, except: [:destroy]
  #before_action :authenticate_admin!
  #before_action :authenticate_super!
  skip_before_action :verify_authenticity_token
  helper_method :get_age

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end
   
  def download   
    send_file @employee.copy_document,
    :filename => "#{File.extname(@employee.file.path)}"      
  end

  def get_age(birthday)
    return age_calculate(birthday)
  end

  def pdf
    @employee = Employee.left_outer_joins(:clinical, :labors, :family_groups , :academics).find(params[:id])
    if @employee.birthday.present?
      @edad = age_calculate(@employee.birthday)
    else
      @edad = ''
    end

    respond_to do |format|
      format.html
      format.pdf do 
        render  :pdf        => "file_name",
                :page_size  => 'A4',
                :dpi        =>'72',
                title: 'Ficha empleado del SiPTeD', 
                :margin     => {:top => 26, :bottom =>21 },
                :header     => {
                  :content  => render_to_string(:template => 'pdf-component/header.pdf.erb')
                },
                :footer     => {
                  :content  => render_to_string(:template => 'pdf-component/footer.pdf.erb')
                }
      end
    end
  end #end pdf

  def show
    cookies[:employee_id] = @employee.id

    # @employee = Employee.joins(:addresses, :city, :state, :country).where(employee_id: cookies[:employee_id]).order(id: :desc).all
    
    # @employee = Employee.joins(:address, :city, :state, :country).where(employee_id: cookies[:employee_id]).order(created_at: :asc).all
    # if @employee.state!= nil
    #   @provincia = State.where(id: @employee.State_id).first
    #   @provincia  = @provincia.name
    # end

    # if @employee.city_id  != nil 
    #   @ciudad = City.where(id: @employee.city_id).first
    #   @ciudad  = @ciudad.name
    # end

    if @employee.birthday.present?
      @edad = age_calculate(@employee.birthday)
    else
      @edad = ''
    end
    

    #Busca la relación de estado civil asociada al empleado
    t = Employee.includes(:family_groups).find(@employee.id)
    if t.present?
      res = t.family_groups.where('family_ties = ? OR family_ties = ?', 'CONYUGE', 'CONCUBINO')
      @civil_state_relationship = res.first
    else
      @civil_state_relationship = nil
    end

  end


  def new
    @employee = Employee.new
     # @employee.addresses.build.cities.build
  end
   
  def edit
    Employee.lock.find(@employee.id)
  end

  def create
    @employee = Employee.new(employee_params) 
    respond_to do |format|
      if @employee.save
        flash[:success] = 'Se ha dado de alta a ' + @employee.last_name + ', '+ @employee.name
        format.html { redirect_to @employee }
        format.json { render :show, status: :created, location: @employee }
      else        
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
        flash[:error] = 'Verifique los campos'
      end
    end
  end 

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        flash[:success] = 'Se a actuaizado los datos de ' + @employee.last_name + ', '+ @employee.name
        format.html { redirect_to @employee}
        format.json { render :show, status: :ok, location: @employee }
      else          
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
         flash[:notice] = 'Se ha eliminado correctamente'
        format.html { redirect_to employees_url}
        format.json { head :no_content }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
       @employee = Employee.find(params[:id])
      
      # @employee = Employee.includes(family_groups: :document_families).find(params[:id])
          # @presupuesto = Budget.includes(budget_details: :product).find(cookies[:budget_id])
    end
    



    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:legajo, :date_of_admission, :nationality, :name, :last_name, :cuil, 
        :document_type, :document_number, :birthday,
        :marital_state, :avatar, :email, :tel_cel, :tel_home, 
         :other_tel, addresses_attributes: [:id, :employee_id, :neighborhood, :address_street, :address_number, 
         :address_floor, :address_floor_apartment_number, :address_monoblock, :city_id, :actual, :_destroy, cities_attributes:[:name] ],
         attachment_files_attributes: [:id, :name,  :document,:commentary, :document_cache, :_destroy]
           )
    end
end




 

app/helpers/employees_helper.rb
module EmployeesHelper

	def link_to_remove_fields(name, f)
		f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
	end
	def link_to_add_fields(name, f, association)
	    new_object = f.object.send(association).klass.new
	    id = new_object.object_id
	    fields = f.fields_for(association, new_object, child_index: id) do |document|
	      render(association.to_s.singularize + "_fields", f: document)
	    end
	    link_to(name, '', class: "add_fields btn btn-success", data: { id: id, fields: fields.gsub("\n", "")})
	end

end
	

app/views/employees/_address_fields.html.erb
<fieldset class="scheduler-border">
  <legend class="scheduler-border"><i class="fa fa-map-marker" aria-hidden="true"></i> Domicilio
  </legend>

    
        <div class="row"><!--row #7 -->
          <div class="col-md-6">
            <div class="field">
              <div class="form-group">
              <%= f.label :address_street, "Avenida - Calle" %>
              <%= f.text_field :address_street, autofocus: true,requiered: false,:class=>"form-control input-sm" ,placeholder: "Avenida Calle" %>  
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="field">
              <div class="form-group">
              <%= f.label :address_number, "Número" %>
              <%= f.text_field :address_number, autofocus: true,requiered: false, :class=>"form-control input-sm" ,placeholder: "Número" %>  
              </div>
            </div>
          </div>

        </div><!--end row#5
        -->
        <div class="row"><!--row #8-->
          <div class="col-md-4">
            <div class="field">
              <div class="form-group">
              <%= f.label :address_floor, "N° de piso" %>
              <%= f.text_field :address_floor, autofocus: true,requiered: false, :class=>"form-control input-sm" ,placeholder: "Piso" %>  
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="field">
              <div class="form-group">
              <%= f.label :address_floor_apartment_number, "N° de Departamento" %>
              <%= f.text_field :address_floor_apartment_number, autofocus: true,requiered: false, :class=>"form-control input-sm" ,placeholder: "Número de Departamento" %>  
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="field">
              <div class="form-group">
              <%= f.label :address_monoblock, "N° de Monoblock" %>
              <%= f.text_field :address_monoblock, autofocus: true,requiered: false, :class=>"form-control input-sm" ,placeholder: "Número de Monoblock" %>  
              </div>
            </div>
          </div>

        </div><!--end row#8 -->
        <div class="row"><!--row #9 -->
          <div class="col-md-12">
            <div class="field">
              <div class="form-group">
              <%= f.label :neighborhood, "Barrio" %>
              <%= f.text_field :neighborhood, autofocus: true,requiered: false, :class=>"form-control input-sm" ,placeholder: "Barrio" %>  
              </div>
            </div>
          </div>

        </div><!--end row#9 -->
        <div class="row">
          <div class="col-md-4">
            <div class="form-group"> 
              <%= f.label :country, "Pais" %>
          <%= f.collection_select  :country, Country.order(:name), :id, :name, include_blank: true  %>
            </div>
          </div>
          
          <div class="col-md-4">
            <div class="form-group">
              <%= f.label :state, 'Provincia' %>
              <%= f.grouped_collection_select :state, Country.order(:name), :states, :name, :id, :name, include_blank: true %>
            </div>
          </div>
          
          <div class="col-md-4">
            <div class="form-group">
              <%= f.label :city_id, 'Ciudad' %>
              <%= f.grouped_collection_select :city_id, State.order(:name), :cities, :name, :id, :name, include_blank: true %>
            </div>
          </div>
        </div> <!-- Fin row -->
        <div class="row">
          <div class="col-md-4">
              <%= f.label "Domicilio actual" %> <br />
            <%= f.check_box :actual %>
          </div>
        </div>
        <%= f.hidden_field :_destroy%>
        <%= link_to 'Eliminar Domicilio <i class="fa fa-times fa-1x" aria-hidden="true"></i>'.html_safe, '#', class: "remove_fields btn btn-danger" %>


</fieldset>

app/views/employees/_print_dialog.html.erb
<div class="modal fade" id="miModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button class="close" aria-hidden="true" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title"><i class="fa fa-print" aria-hidden="true"></i>
 Secciones a imprimir </h4>
                        </div>
   <%= form_tag pdf_employee_path( id: @employee.id, format: :pdf, :html => {:class => "form_print_dialog"}), :target => '_blank' do  %>
                        <div class="modal-body">
                   
                
                      
                              
                         <ul class="list-group">
                            <li class="list-group-item">
                              Datos Contacto
                            <div class="material-switch pull-right">
                            <%= check_box_tag :contacto %>
                            <label for="contacto" class="label-success"></label>
                            </div>
                            </li>
                             <li class="list-group-item">
                            Domicilio
                            <div class="material-switch pull-right">
                            <%= check_box_tag :domicilio %>
                            <label for="domicilio" class="label-success"></label>
                            </div>
                            </li>
                            <li class="list-group-item">
                            Datos Laboral (solo se imprimirán los activos)
                            <div class="material-switch pull-right">
                            <%= check_box_tag :laboral %>
                            <label for="laboral" class="label-success"></label>
                            </div>
                            </li>
                            <li class="list-group-item">
                            Datos Medico
                            <div class="material-switch pull-right">
                            <%= check_box_tag :medico %>
                            <label for="medico" class="label-success"></label>
                            </div>
                            </li>
                             <li class="list-group-item">
                            Datos Familiares
                            <div class="material-switch pull-right">
                            <%= check_box_tag :familia %>
                            <label for="familia" class="label-success"></label>
                            </div>
                            </li>
                         </ul>
                        </div>

                        <div class="modal-footer">
                    <button class="btn btn-default"  type="submit" onclick="closePrint()">Imprimir</button>
                   
                            <button class="btn btn-default" data-dismiss="modal">Cancelar</button>                           
                        </div>
                          <%end%>


                    </div>
                </div>
            </div> 

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Legajo</th>
      <th>Name</th>
      <th>Last name</th>
      <th>Cuil</th>
      <th>Document type</th>
      <th>Document number</th>
      <th>Category</th>
      <th>Function employee</th>
      <th>Marital state</th>
      <th>Relationship of dependency</th>
      <th>Avatar</th>
      <th>Date of admission</th>
      <th>Active</th>
      <th>City</th>
      <th>Location</th>
      <th>State</th>
      <th>Country</th>
      <th>Neighborhood</th>
      <th>Address street</th>
      <th>Address number</th>
      <th>Address floor</th>
      <th>Address floor apartment number</th>
      <th>Address monoblock</th>
      <th>Making performance</th>
      <th>Legal instrument</th>
      <th>Email</th>
      <th>Tel cel</th>
      <th>Tel home</th>
      <th>Other tel</th>
      <th>Tel emergency</th>
      <th>Name contact</th>
      <th>Tel work</th>
      <th>Interno tel work</th>
      <th>Email work</th>
      <th>Name social work</th>
      <th>Number partner</th>
      <th>Blood type</th>
      <th>Allergies</th>
      <th>Background</th>
      <th>Leaving date</th>
      <th>Reason</th>
      <th>Clinical analyzes</th>
      <th>Suitable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.legajo %></td>
        <td><%= employee.name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.cuil %></td>
        <td><%= employee.document_type %></td>
        <td><%= employee.document_number %></td>
        <td><%= employee.category %></td>
        <td><%= employee.function_employee %></td>
        <td><%= employee.marital_state %></td>
        <td><%= employee.relationship_of_dependency %></td>
        <td><%= employee.avatar %></td>
        <td><%= employee.date_of_admission %></td>
        <td><%= employee.active %></td>
        <td><%= employee.city %></td>
        <td><%= employee.location %></td>
        <td><%= employee.state %></td>
        <td><%= employee.country %></td>
        <td><%= employee.neighborhood %></td>
        <td><%= employee.address_street %></td>
        <td><%= employee.address_number %></td>
        <td><%= employee.address_floor %></td>
        <td><%= employee.address_floor_apartment_number %></td>
        <td><%= employee.address_monoblock %></td>
        <td><%= employee.making_performance %></td>
        <td><%= employee.legal_instrument %></td>
        <td><%= employee.email %></td>
        <td><%= employee.tel_cel %></td>
        <td><%= employee.tel_home %></td>
        <td><%= employee.other_tel %></td>
        <td><%= employee.tel_emergency %></td>
        <td><%= employee.name_contact %></td>
        <td><%= employee.tel_work %></td>
        <td><%= employee.interno_tel_work %></td>
        <td><%= employee.email_work %></td>
        <td><%= employee.name_social_work %></td>
        <td><%= employee.number_partner %></td>
        <td><%= employee.blood_type %></td>
        <td><%= employee.allergies %></td>
        <td><%= employee.background %></td>
        <td><%= employee.leaving_date %></td>
        <td><%= employee.reason %></td>
        <td><%= employee.clinical_analyzes %></td>
        <td><%= employee.suitable %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/show.html.erb
<!-- modal para imprimir -->
<%= render 'print_dialog' %> 
<div class="main_container">
  <div  role="main">       
    <div class="page-title">         
      <div class="title_right"></div>
      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Empleado del SiPTeD</h2>
              <div class="btn-action">
                <%= link_to '<i class="fa fa-undo" aria-hidden="true"></i>'.html_safe, root_path(),  class: 'btn btn-default tag-tooltip', :data => {:toggle=>"tooltip"}, 'data-original-title' => "Volver al Listado"%><span>

                <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_employee_path(@employee),class: 'btn btn-default tag-tooltip', :data => {:toggle=>"tooltip"}, 'data-original-title' => "Editar"%><span>

                <button class="btn btn-default" title="Imprimir" data-toggle="modal"  data-target="#miModal">
                  <i class="fa fa-print" aria-hidden="true"></i>
                </button>    
                    
                <%= link_to 'Formación Académica <i class="fa fa-graduation-cap" aria-hidden="true"></i>'.html_safe, academics_path(:id => @employee.id),class: 'btn btn-default tag-tooltip', :data => {:toggle=>"tooltip"}, 'data-original-title' => "Formación Académica"%><span>

                <%= link_to 'Laboral <i class="fa fa-handshake-o" aria-hidden="true"></i>'.html_safe, labors_path(:id => @employee.id),class: 'btn btn-default tag-tooltip' , :data => {:toggle=>"tooltip"}, 'data-original-title' => "Laboral"%><span>

                <%= link_to 'Datos Medicos <i class="fa fa-medkit" aria-hidden="true"></i>'.html_safe, clinicals_path(:ids => @employee.id),class: 'btn btn-default tag-tooltip' , :data => {:toggle=>"tooltip"}, 'data-original-title' => "Datos Medicos"%><span>

                <%= link_to 'Grupo Familiar <i class="fa fa-users" aria-hidden="true"></i>'.html_safe, family_groups_path,class: 'btn btn-default tag-tooltip' , :data => {:toggle=>"tooltip"}, 'data-original-title' => "Grupo Familiar"%><span>

                <%= link_to 'LAO <i class="fa fa-calendar-o" aria-hidden="true"></i>'.html_safe, '#', class: 'btn btn-default tag-tooltip' , :data => {:toggle=>"tooltip"}, :disabled => true, 'data-original-title' => "Licencia Anual Ordinaria"%><span>
              </div>

              <div class="clearfix"></div>
            </div>

            <div class="x_content">
              <div class="col-md-2 col-sm-2 col-xs-12 profile_left">
                <div class="profile_img">
                  <div id="crop-avatar">
                    <!-- Current avatar -->
                    <% unless @employee.avatar.blank? %>   
                      <%=image_tag(@employee.avatar.url, class:"img-responsive avatar-view")%>     
                    <%else%>
                      <%=image_tag("users/default_avatar.png", class:"img-responsive avatar-view")%>
                    <%end%>
                  </div>
                </div>
                <h3>  Legajo <strong><%= @employee.legajo %> </strong> </h3>
              </div>
              <div class="col-md-10 col-sm-10 col-xs-12">
                <div class="profile_title">
                  <div class="col-md-12">                  
                    <h2><%= @employee.last_name %> <%= @employee.name %></h2>         
                  </div>    
                </div>                                       
                <!-- datos del contacto-->
                <div class="panel panel-default">
                  <div class="panel-heading">Datos del Contacto</div>
                    <div class="panel-body">                       
                      <div class="row"><!--row#1 #2 -->
                        <div class="col-md-6">
                          <div class="field">
                            <div class="form-group">
                              <strong>Apellido y Nombre:</strong>
                              <%= @employee.last_name %>,  <%= @employee.name %>                 
                            </div>
                          </div>
                        </div>
                      </div><!--end row#2 -->
                      <div class="row"><!--row #3 -->
                        <div class="col-md-4">
                          <div class="field">
                            <div class="form-group">          
                              <strong>Tipo y Num. documento:</strong>
                              <%= @employee.document_type %> - <%= @employee.document_number %>    
                            </div>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="form-group">
                            <strong>Fecha de Nacimiento:</strong>
                            <%= @employee.birthday !=nil ? (@employee.birthday.strftime "%d/%m/%Y") : '' %>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="field">
                            <div class="form-group">       
                              <strong>Nacionalidad:</strong>
                              <%= @employee.nationality %>    
                            </div>
                          </div>
                        </div>
                      </div><!--end row#3 -->        
                      <div class="row"><!--row#4 -->
                        <div class="col-md-6">
                          <div class="field">
                            <div class="form-group">
                              <strong>Email:</strong>
                              <%= @employee.email %>         
                            </div>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="field">
                            <div class="form-group">     
                              <strong>CUIL:</strong>
                              <%= @employee.cuil %>     
                            </div>
                          </div>
                        </div>
                      </div><!--end row#4 -->
                      <div class="row"><!--row #5 -->
                        <div class="col-md-4">
                          <div class="field">
                            <div class="form-group">    
                              <strong>Celular:</strong>
                              <%= @employee.tel_cel %>      
                            </div>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="field">
                            <div class="form-group">        
                              <strong>Teléfono casa:</strong>
                              <%= @employee.tel_home %>     
                            </div>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="field">
                            <div class="form-group">        
                              <strong>Otro telefono:</strong>
                              <%= @employee.other_tel %>    
                            </div>
                          </div>
                        </div>
                      </div><!--end row#5 -->
                      <div class="row"><!--row #6-->
                        <div class="col-md-6">
                          <div class="field">
                            <div class="form-group">                                   
                              <strong>Estado civil:</strong>
                              <%= @employee.marital_state %>
                              <% if @civil_state_relationship.present? %>
                                - 
                                <%= link_to(@civil_state_relationship, class: "civil_state", data: {modal: true}) do %>
                                  <i class="fa fa-user" aria-hidden="true"></i>
                                  <%= [@civil_state_relationship.last_name, @civil_state_relationship.name].join(', ') %>           
                                <%end%>
                              <%end%>                             
                            </div>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                            <strong>Edad:</strong>
                            <%= @edad%>
                          </div>
                        </div>                   
                      </div><!--end row#5  -->
                      <div class="row">
                        <div class="col-md-6">
                          <div class="field">
                            <div class="form-group">
                              <strong>Fecha de Ingreso al Organismo:</strong>
                              <%= @employee.date_of_admission.present? ? @employee.date_of_admission.strftime("%d/%m/%Y") : '-' %>
                            </div>
                          </div>
                        </div>
                      </div>          
                    </div>
                  </div>
                  <!-- fin bloque datos del contacto-->
                  <!--  bloque domicilio del contacto-->
                  <div class="panel panel-default">
                    <div class="panel-heading">Domicilio</div>
                    <div class="panel-body">
                      <%= render "showAddress"%>
                    </div>
                  </div>
                  <!--  fin bloque domicilio del contacto-->
                  <div class="panel panel-default">
                    <div class="panel-heading">Documentos Adjuntos</div>                        
                      <div class="row">
                        <div class="col-md-12">
                         

                          <div id="atachement_employe">
                                <%= render "table_attachament_employe"%>
                          </div>
                        </div> <!-- end row documentos adjuntos -->
                      </div>
                    </div> <!-- end panel documentos adjuntos  -->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      thecheck();
    </script>