config/routes.rb
Rails.application.routes.draw do
  resources :document_academics
  resources :academics
  resources :clinicals
  get 'document_family/index'
  mount Judge::Engine => '/judge'
  # ActiveAdmin.routes(self)
  # devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  namespace :dynamic_selectable do
    get 'departments/:department_id/functions', to: 'department_functions#index', as: :department_functions
    get 'directions/:direction_id/departments', to: 'direction_departments#index', as: :direction_departments
    get 'general_directions/:general_direction_id/directions', to: 'general_direction_directions#index', as: :general_direction_directions
  end


  resources :general_directions
  resources :functions
  resources :departments
  resources :directions
  resources :labors

  get '/unexpired_contracts' => 'labors#unexpired_contracts'
  get '/full_age' => 'family_groups#full_age'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, path: '/', only: [:sessions]
  devise_scope :user do
  	get "login", to: "devise/sessions#new"

    authenticated :user, lambda {|u| u.role == "admin"} do
      root to: "home#index", as: :authenticated_root
    end

    authenticated :user, lambda {|u| u.role == "none"} do
      root to: "home#index"
    end

    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_root
    end
  end


	get 'home/index'

	resources :family_groups do
    member do
      get 'download'
    end
  end


	resources :employees do
		member do
  		post "pdf"
      get 'download'
  	end
	end

  resources :home do
    member do
      post "listpdf"
    end
  end

end

app/models/family_group.rb
require 'carrierwave/orm/activerecord'
class FamilyGroup < ApplicationRecord
	has_many :attachment_files, :as => :imageable
	accepts_nested_attributes_for :attachment_files,  allow_destroy: true

	belongs_to :employee, optional: true
	#Paper Trail se usa para el log
	has_paper_trail :on => [:create, :update, :destroy], :ignore => [:update_at, :created_at, :employee_id]

	validates :name,  presence:  { message: "Campo obligatorio" }
	validates :last_name,  presence:  { message: "Campo obligatorio" }
	validates :document_numbre,  presence:  { message: "Campo obligatorio" }
	validates :name, :last_name, format: { with: /[a-zA-Z]+/, message: "se permiten solo letras" }
	extend Enumerize
	enumerize :family_ties, in:[:'CONYUGE', :'CONCUBINO', :'PADRE', :'MADRE', :'HIJO/A', :'HERMANO/A', :'OTROS']

end

app/controllers/family_groups_controller.rb
class FamilyGroupsController < ApplicationController
  before_action :set_family_group, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  respond_to :html, :json
  helper_method :get_age

  def index
    @family_group = FamilyGroup.new
    #Si se ingresa al #index#FamilyGroup desde un empleado, entonces cookies[:employee_id] != nil
    if cookies[:employee_id].present?
      @employee = Employee.find(cookies[:employee_id])
      @family_groups = FamilyGroup.where(employee_id: cookies[:employee_id]).all
    else #Si se ingresa desde el #root, cookies[:employee_id] == nil y params[:employee_id] sera el que tenga el id de empleado
      if params[:employee_id].present?
        cookies[:employee_id] = params[:employee_id]
        @employee = Employee.find(params[:employee_id])
        @family_groups = FamilyGroup.where(employee_id: params[:employee_id]).all
      end
    end
  end

  def get_age(birthday)
    return age_calculate(birthday)
  end


  def download
    puts "----------------- download ----------------"
    @attachment_file = AttachmentFile.find(params[:id])
    
    send_file(@attachment_file.document.path,
      :disposition => 'attachment',
      :url_based_filename => false)            
  end

  def show
    if params[:object].present?
      @family_group = FamilyGroup.where(id: params[:object]).first
      puts @family_group.inspect
    end
    respond_modal_with @family_group
  end

  def new
    has_relationship()
    @family_group = FamilyGroup.new
    respond_modal_with @family_group
  end

  #Verifica si existe una relacion 'family_ties' de tipo Conyuge o Concubino con un Empleado
  def has_relationship
    @query = FamilyGroup.where("employee_id= ? AND (family_ties= ? OR family_ties= ?)", cookies[:employee_id], "CONYUGE", "CONCUBINO")
  end

  # GET /family_groups/1/edit
  def edit
    puts @family_group.family_ties.inspect
    if @family_group.family_ties != "CONYUGE" && @family_group.family_ties != "CONCUBINO"
      @query = 0
      puts @query.inspect
    end
    respond_modal_with @family_group.attachment_files
  end

  def create
    @employee = Employee.find(cookies[:employee_id])
    @family_group = FamilyGroup.new(family_group_params)
    @family_group.employee_id = @employee.id
    if @family_group.save
      flash[:success] = 'Los datos familiares se guardaron exitosamente.'
      respond_modal_with @family_group, location: family_groups_path  
    end
  end

  def update
    # if has_relationship().present? #True si existe relación
    #   flash[:warning] = 'Error. ¡Ya existe este tipo de familiar para este empleado!'
    #   respond_modal_with @family_group, location: family_groups_path  
    # else
      respond_to do |format|
        if @family_group.update(family_group_params)
           flash[:notice] ='Se actualizó el Familiar.' 
          format.html { redirect_to family_groups_path }
          format.json { render :index, status: :ok, location: @family_group }
        else
          format.html { render :edit }
          format.json { render json: @family_group.errors, status: :unprocessable_entity }
        end
      end
    #end
  end

  def destroy
    @family_group.destroy
    respond_to do |format|
       flash[:warning] ='El dato familiar ha sido eliminado.'
      format.html { redirect_to family_groups_url}
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family_group
      @family_group = FamilyGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_group_params
      params.require(:family_group).permit(:family_ties, :Birthday, :age, :name, :last_name, :document_numbre, :live, :employee_id, attachment_files_attributes: [:id, :name, :document, :document_cache, :commentary, :_destroy])
    end
end

app/helpers/family_groups_helper.rb
module FamilyGroupsHelper
	def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |document|
      render(association.to_s.singularize + "_fields", f: document)
    end
    link_to(name, '', class: "add_fields btn btn-success", data: { id: id, fields: fields.gsub("\n", "")})
  end






end

app/views/family_groups/_attachment_file_fields.html.erb
<fieldset>
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6 col-sm-6 col-md-6">
					<div class="form-group ">
						<%= f.file_field :document, class: "btn btn-default btn-doc", :required => true %>
						<%= f.hidden_field :document_cache %>									
					</div>
				</div> 
				<div class="col-md-6">
					<div class="form-group">
						<%= f.text_area :commentary, class: "form-control area", rows: 2, placeholder: "* Comentario", :required => true %>
					</div>
				</div>				
    	</div>
    	<div class="row">
    		<div class="col-md-12">
    			<%= f.hidden_field :_destroy %>
		  		<%= link_to  'Eliminar Documento <i class="fa fa-times fa-1x" aria-hidden="true"></i>'.html_safe, '#', class: "remove_fields btn btn-danger" %>
    		</div>
    	</div>
		</div> 
	</div>
</fieldset>

app/views/family_groups/_form.html.erb
<% if family_group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(family_group.errors.count, "error") %> prohibited this clinical from being saved:</h2>
    <ul>
    <% family_group.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
    <%= form_for(@family_group, :builder => Judge::FormBuilder ,remote: request.xhr?, html: { data: { modal: true  } }) do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="field">
            <div class="form-group">
              <%= f.label :family_ties, "Relacion Familiar" %>
              <% if @query.present? %>
                <%= f.select :family_ties, options_for_select(["PADRE", "MADRE", "HIJO/A", "HERMANO/A", "OTROS"]), class: "form-control input-sm"%>
              <%else%>
                <%= f.select :family_ties, FamilyGroup.family_ties.options ,{}, class: "form-control input-sm" %> 
              <%end%>
            </div>
          </div>
        </div>           
      </div>
      
      <div class="row">
        <div class="col-md-6">
          <div class="field">
            <div class="form-group">
              <%= f.label :name , "Nombre" %>
              <p class="errores" id="family_group_name"><%= @family_group.errors[:name].to_s[/\w([^"]*)/] %></p>
              <%= f.text_field :name,:validate => true, autofocus: true,:class=>"form-control input-xs validation" ,placeholder: "Nombre", :required => true %>         
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :last_name , "Apellido" %>
            <p class="errores" id="family_group_last_name"><%= @family_group.errors[:last_name].to_s[/\w([^"]*)/] %></p>
            <%= f.text_field :last_name,:validate => true, autofocus: true,:class=>"form-control input-xs validation" ,placeholder: "Apellido", :required => true %> 
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="col-md-6">
          <div class="field">
            <div class="form-group">
              <%= f.label :document_numbre , "Numero de Documento" %>
              <p class="errores" id="family_group_document_numbre"><%= @family_group.errors[:document_numbre].to_s[/\w([^"]*)/] %></p>
              <%= f.text_field :document_numbre,:validate => true, autofocus: true,requiered: false,:class=>"form-control input-xs validation" ,placeholder: "Numero de Documento", :required => true %> 
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
<!--             <%= f.label :cuil , "CUIL" %>
            <%= f.text_field :cuil, autofocus: true,requiered: false,:class=>"form-control input-xs" ,placeholder: "CUIL" %>  -->
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="input-group">
            <%= f.label :Birthday, "Fecha de nacimiento" %>
            <% fecha = @family_group.Birthday !=nil ? (@family_group.Birthday.strftime "%d/%m/%Y") : '' %>
            <%= f.text_field :Birthday, :class => 'datepicker', value: fecha , 'placeholder'=> "dd-mm-yyyy"  %><br/>
          </div>
        </div>

        <div class="col-md-6">
          <div class="input-group">
            <%= f.label :live, "¿Vive?" %>
            <%= f.check_box :live, {'type' => 'checkbox'} %>  
          </div>
        </div>
      </div>
      <br/>
        <div class="field">
          <div class="form-group ">
            <%= f.fields_for :attachment_files do |attachment| %>
              <%= render 'attachment_file_fields', f: attachment %>
            <%end%>  
            <%= link_to_add_fields 'Agregar Documento Adjunto <i class="fa fa-plus fa-1x" aria-hidden="true"></i>'.html_safe, f, :attachment_files %> 
          </div>
        </div>
        <div class="btn-action">
          <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
            <i class="fa fa-floppy-o " aria-hidden="true"></i>
              Guardar
          <% end %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        </div>       
    <%end%>

  <script>
    $( document ).ready(function() {  
$('.validation').on('input select', function() {
    judge.validate($(this)[0], {
    
        valid: function(element) {
                element.style.border = '2px solid green';
                 $("p").fadeOut();
                var name = $('input[id="family_group_name"]').val();
                var last_name = $('input[id="family_group_last_name"]').val();
                 var document_numbre = $('input[id="family_group_document_numbre"]').val();
                
                if (name.length == 0 || last_name.length == 0  || document_numbre.length == 0){
                  console.log ("no pasa");
                  // $('button:submit').attr("disabled", true);
                }else{
                  // $('button:submit').attr("disabled", false);
                  console.log("pasa");
                }
        },
        invalid: function(element, messages) {
              console.log(element.id);
          // $('button:submit').attr("disabled", true);
           element.style.border = '2px solid red';
           document.getElementById(element.id).innerHTML = (messages.join(','));
           console.log("*****************");
           console.log(element.id);
           $('#'+element.id).fadeIn("slow");

          }
    });
 });


    $('.datepicker').datepicker({dateFormat: 'dd/mm/yyyy',
        language: 'es',
        startView: 2  
    });

});
  </script>

app/views/family_groups/_full_age.html.erb
<!-- Vista parcial donde se muestra los hijos de empleados que estan proximos a cumplir la mayoria de edad. -->
<div class="panel-body">
    <small><p>Hijos de empleados, próximos a cumplir la mayoria de edad.</p></small>
</div>
<table class="table table-condensed max-height-200 overflow">
	<tbody>
		<% @full_age.map { |obj| %>
			<tr class="warning">
				<td>
					<small><strong>
						<%=obj.last_name%>, <%=obj.name%>
					</strong></small><br>
					<small class="text-muted">
						<abbr title="Empleado"><%=obj.employee.last_name%>, <%=obj.employee.name%>/<%=obj.employee.legajo%></abbr>
					</small>
				</td>
				<td>
					<small>
          				<%= obj.Birthday != nil ? (obj.Birthday.strftime "%d/%b") : '' %>
         			</small>
             	</td>
             	<td>
					<%= link_to '<i class="fa fa-arrow-right" aria-hidden="true"></i>'.html_safe, family_group_path(obj, :object => obj.id), data: {modal: true} %> 
             	</td>
			</tr>
		<% } %>
	</tbody>
</table>

app/views/family_groups/edit.html.erb
<% content_for :title, "Editar Familiar" %> 
                             
<%= render 'form', family_group: @family_group %>

app/views/family_groups/index.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Datos de Familiares</h2>
    <div class="btn-action">
      <%= link_to '<i class="fa fa-user-plus" aria-hidden="true"></i>'.html_safe, new_family_group_path, data:{ modal: true, :toggle=>"tooltip"}, class: 'btn btn-default tag-tooltip', 'data-original-title' => "Agregar Familiar"   %>

      <%= link_to 'Volver<i class="fa fa-undo" aria-hidden="true"></i>'.html_safe,employee_path(@employee) ,class: 'btn btn-default tag-tooltip', :data => {:toggle=>"tooltip"}, 'data-original-title' => "Volver"   %>  
    </div>  
    <div class="clearfix"></div>
</div>

<%= render "partials/header_employee"%>
<!-- <br>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= link_to 'Agregar Familiar <i class="fa fa-user-plus" aria-hidden="true"></i>'.html_safe, new_family_group_path,data: { modal: true },class: 'btn btn-default btn-lg btn-block'  %> <span></span>
  </div>
</div>
<br/  > -->
<% if @family_groups.any?  %>
  <% @family_groups.each do |family_group| %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
          <div class="panel-heading"><%= family_group.family_ties  %>
            <div class="btn-action">
              <%= link_to '<i class="fa fa-pencil-square-o fa-1x" aria-hidden="true"></i>'.html_safe, edit_family_group_path(family_group), class: "btn btn-primary  btn-xs tag-tooltip",:data => {:toggle=>"tooltip", modal: true},
                    'data-original-title' => "Editar" %><span></span>

              <%= link_to '<i class="fa fa-trash-o  fa-1x" aria-hidden="true"></i>'.html_safe, family_group, method: :delete, class: "btn btn-danger btn-xs tag-tooltip",:data => {:toggle=>"tooltip", confirm: '¿Seguro que desea eliminar este Familiar?'},
                    'data-original-title' => "Eliminar" %><span></span>
            </div>
          </div>
          <div class="panel-body">                             
            <div class="row">
              <div class="col-md-6">
                <div class="field">
                  <div class="form-group">
                    <strong>Relacion familiar:</strong>
                    <%= family_group.family_ties  %> 
                  </div>
                </div>
              </div>                             
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="field">
                  <div class="form-group">
                    <strong>Nombre</strong>
                    <%=  family_group.name %> 
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <strong>Apellido</strong>
                  <%= family_group.last_name %> 
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="field"> 
                  <div class="form-group">
                    <strong>N. Documento</strong>
                    <%= family_group.document_numbre  %> 
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <strong>C.U.I.L:</strong>
                  <%= family_group.cuil %> 
                </div>
              </div>
            </div>
            <div class="row"> 
              <div class="col-md-6">
                <div class="form-group">
                  <strong>Fecha de Nacimiento:</strong>
                  <%=   family_group.Birthday !=nil ? (family_group.Birthday.strftime "%d/%m/%Y") : ''   %>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <strong>Edad:</strong>
                  <%= family_group.Birthday.present? ? get_age(family_group.Birthday) : '' %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <% family_group.attachment_files.each do |doc| %>           
                  <div class="form-group">
                    <% if doc.document %>
                      <div class="row">
                        <div class="col-md-12">
                          <span>
                            <%= link_to '<i class="fa fa-paperclip" aria-hidden="true"></i>'.html_safe, doc.document_url,  :target => "_blank", class: "btn btn-default btn-xs"%>
                            <% unless doc.commentary.blank? %>
                              <%= doc.commentary %>
                            <%else%>
                              Descripcion sin especificar
                            <%end%>            
                          </span>                
                        </div>
                      </div>
                    <%end%>
                  </div>
                <%end%>
              </div>    
            </div>
          </div> <!-- Fin panel-body -->
        </div>
      </div>
    </div> <!-- Fin row -->
  <%end%>
<% else %>
  <fieldset class="msj-border"><br/>
    <div class="alert alert-warning">
      <h3><strong>Aun no se a agregado ningun Familiar </strong> <span class="label label-warning"><i class="fa fa-exclamation " aria-hidden="true"></i></span></h3>
    </div>
  </fieldset>
  </div>
</div>
<%end%>
<br>
</div> 
  <!-- Trigger the modal with a button -->
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Agregar Familiar</h4>
        </div>
        <div class="modal-body">
             <%= render 'form', family_group: @family_group %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>


  

               
             

app/views/family_groups/new.html.erb
<% content_for :title, "Nuevo Familiar" %>                           
<%= render 'form', family_group: @family_group %>

app/views/family_groups/show.html.erb
<% content_for :title, "Familiar" %>
<div class="well">

  <div class="row">
    <div class="col-md-6">
      <div class="field">
        <div class="form-group">
          <strong>Relación Familiar: </strong>
          <%= @family_group.family_ties %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="field">
        <div class="form-group">
          <strong>Apellido y Nombre: </strong>
          <%= @family_group.last_name %>, <%= @family_group.name %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="field">
        <div class="form-group">
          <strong>Número de DNI: </strong>
          <%= @family_group.document_numbre %>
        </div>
      </div>
    </div>
  </div>

  <!-- <div class="row">
    <div class="col-md-6">
      <div class="field">
        <div class="form-group">
          <strong>Número de CUIL: </strong>
          <%= @family_group.cuil %>
        </div>
      </div>
    </div>
  </div> -->

  <div class="row">
    <div class="col-md-6">
      <div class="field">
          <% @family_group.document_families.each do |doc| %>
          <div class="form-group">
            <%  if doc.document %>
            <div class="row">
              <div class="col-md-12">
                <span>
                  <%= link_to '<i class="fa fa-paperclip" aria-hidden="true"></i>'.html_safe, doc.document_url,  :target => "_blank", class: "btn btn-default btn-xs" %>
                  <% unless doc.commentary.blank? %>
                    <%= doc.commentary %>
                  <% else %>
                    Descripción sin especificar
                  <% end %>
                </span>
              </div>
            </div>
            <% end %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
  
  <div class="row">    
    <div class="col-md-6">    
      <div class="btn-action">
        <%= link_to 'Ir a familiares <i class="fa fa-arrow-right" aria-hidden="true"></i>'.html_safe, family_groups_path(@family_group, :employee_id => @family_group.employee_id), class: 'btn btn-success'  %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div> <!-- Fin div well -->