config/routes.rb
Rails.application.routes.draw do
  resources :document_academics
  resources :academics
  resources :clinicals
  get 'document_family/index'
  mount Judge::Engine => '/judge'
  # ActiveAdmin.routes(self)
  # devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  namespace :dynamic_selectable do
    get 'departments/:department_id/functions', to: 'department_functions#index', as: :department_functions
    get 'directions/:direction_id/departments', to: 'direction_departments#index', as: :direction_departments
    get 'general_directions/:general_direction_id/directions', to: 'general_direction_directions#index', as: :general_direction_directions
  end


  resources :general_directions
  resources :functions
  resources :departments
  resources :directions
  resources :labors

  get '/unexpired_contracts' => 'labors#unexpired_contracts'
  get '/full_age' => 'family_groups#full_age'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, path: '/', only: [:sessions]
  devise_scope :user do
  	get "login", to: "devise/sessions#new"

    authenticated :user, lambda {|u| u.role == "admin"} do
      root to: "home#index", as: :authenticated_root
    end

    authenticated :user, lambda {|u| u.role == "none"} do
      root to: "home#index"
    end

    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_root
    end
  end


	get 'home/index'

	resources :family_groups do
    member do
      get 'download'
    end
  end


	resources :employees do
		member do
  		post "pdf"
      get 'download'
  	end
	end

  resources :home do
    member do
      post "listpdf"
    end
  end

end

app/models/general_direction.rb
class GeneralDirection < ApplicationRecord
  #belongs_to :direction
  #belongs_to :department
  #has_many :departments
  has_many :directions
  validates :name, presence: true, uniqueness: true
end

app/controllers/general_directions_controller.rb
class GeneralDirectionsController < ApplicationController
  before_action :set_general_direction, only: [:show, :edit, :update, :destroy]

  # GET /general_directions
  # GET /general_directions.json
  def index
    @general_directions = GeneralDirection.all
  end

  # GET /general_directions/1
  # GET /general_directions/1.json
  def show
  end

  # GET /general_directions/new
  def new
    @general_direction = GeneralDirection.new
  end

  # GET /general_directions/1/edit
  def edit
  end

  # POST /general_directions
  # POST /general_directions.json
  def create
    @general_direction = GeneralDirection.new(general_direction_params)

    respond_to do |format|
      if @general_direction.save
        format.html { redirect_to @general_direction, notice: 'General direction was successfully created.' }
        format.json { render :show, status: :created, location: @general_direction }
      else
        format.html { render :new }
        format.json { render json: @general_direction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /general_directions/1
  # PATCH/PUT /general_directions/1.json
  def update
    respond_to do |format|
      if @general_direction.update(general_direction_params)
        format.html { redirect_to @general_direction, notice: 'General direction was successfully updated.' }
        format.json { render :show, status: :ok, location: @general_direction }
      else
        format.html { render :edit }
        format.json { render json: @general_direction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /general_directions/1
  # DELETE /general_directions/1.json
  def destroy
    @general_direction.destroy
    respond_to do |format|
      format.html { redirect_to general_directions_url, notice: 'General direction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_general_direction
      @general_direction = GeneralDirection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def general_direction_params
      params.require(:general_direction).permit(:name)
    end
end

app/helpers/general_directions_helper.rb
module GeneralDirectionsHelper
end

app/views/general_directions/_form.html.erb
<%= form_for(general_direction) do |f| %>
  <% if general_direction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(general_direction.errors.count, "error") %> prohibited this general_direction from being saved:</h2>

      <ul>
      <% general_direction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :direction_id %>
    <%= f.text_field :direction_id %>
  </div>

  <div class="field">
    <%= f.label :department_id %>
    <%= f.text_field :department_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/general_directions/edit.html.erb
<h1>Editing General Direction</h1>

<%= render 'form', general_direction: @general_direction %>

<%= link_to 'Show', @general_direction %> |
<%= link_to 'Back', general_directions_path %>

app/views/general_directions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>General Directions</h1>

<table>
  <thead>
    <tr>
      <th>Direction</th>
      <th>Department</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @general_directions.each do |general_direction| %>
      <tr>
        <td><%= general_direction.direction %></td>
        <td><%= general_direction.department %></td>
        <td><%= general_direction.name %></td>
        <td><%= link_to 'Show', general_direction %></td>
        <td><%= link_to 'Edit', edit_general_direction_path(general_direction) %></td>
        <td><%= link_to 'Destroy', general_direction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New General Direction', new_general_direction_path %>

app/views/general_directions/new.html.erb
<h1>New General Direction</h1>

<%= render 'form', general_direction: @general_direction %>

<%= link_to 'Back', general_directions_path %>

app/views/general_directions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Direction:</strong>
  <%= @general_direction.direction %>
</p>

<p>
  <strong>Department:</strong>
  <%= @general_direction.department %>
</p>

<p>
  <strong>Name:</strong>
  <%= @general_direction.name %>
</p>

<%= link_to 'Edit', edit_general_direction_path(@general_direction) %> |
<%= link_to 'Back', general_directions_path %>