config/routes.rb
Rails.application.routes.draw do
  resources :document_academics
  resources :academics
  resources :clinicals
  get 'document_family/index'
  mount Judge::Engine => '/judge'
  # ActiveAdmin.routes(self)
  # devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  namespace :dynamic_selectable do
    get 'departments/:department_id/functions', to: 'department_functions#index', as: :department_functions
    get 'directions/:direction_id/departments', to: 'direction_departments#index', as: :direction_departments
    get 'general_directions/:general_direction_id/directions', to: 'general_direction_directions#index', as: :general_direction_directions
  end


  resources :general_directions
  resources :functions
  resources :departments
  resources :directions
  resources :labors

  get '/unexpired_contracts' => 'labors#unexpired_contracts'
  get '/full_age' => 'family_groups#full_age'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, path: '/', only: [:sessions]
  devise_scope :user do
  	get "login", to: "devise/sessions#new"

    authenticated :user, lambda {|u| u.role == "admin"} do
      root to: "home#index", as: :authenticated_root
    end

    authenticated :user, lambda {|u| u.role == "none"} do
      root to: "home#index"
    end

    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_root
    end
  end


	get 'home/index'

	resources :family_groups do
    member do
      get 'download'
    end
  end


	resources :employees do
		member do
  		post "pdf"
      get 'download'
  	end
	end

  resources :home do
    member do
      post "listpdf"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
	respond_to  :html, :json

    
	def index

		#limpieza profunda de galletitas
		if cookies[:employee_id].present?
			cookies.delete :employee_id
		end
		@search = Employee.left_outer_joins(:clinical, :family_groups, :academics)
					.includes(:labors)
					.order('legajo DESC')
					.search(params[:q])
		puts "**********************************"
		puts @search.inspect
		@@pepe = @search # -> Ver por pepe en método 'listpdf'
		@employee = @search.result(distinct: true)
		@employee = @employee.page(params[:page]).per(10)
		@labors = Labor.joins(:general_direction, :direction, :department, :function, :employee)
					.order(departure_date: :asc)
					.all

		#CANTIDAD de contratos por vencer
		@count = expired_counts(@labors)			
					
		if params[:q].present?
			cookies[:regimen] =  params["q"]["regimen_start"]
			cookies[:category] =  params["q"]["category_start"]
			cookies[:manyinputs] =  params["q"]["last_name_or_name_or_legajo_or_email_cont_any"]
		end

		# Hijos próximos a cumplir la mayoria de edad
		@family_groups = FamilyGroup.left_outer_joins(:employee).where(family_ties: "HIJO/A").distinct
		@full_age ||= Array.new
		@family_groups.each do |f|
			if f.Birthday.present?
				if age_calculate(f.Birthday) == 17 #Ver que otra bandera se puede usar para Hijos que ya hayan cumplido la mayoria de edad.
					if (expires_in = calculate_days(f.Birthday, 31)) != nil #Cantidad de dias que faltan para cumplir 18
						@full_age << f
					end
				end
			end
		end

      respond_to do |format|
        format.html
        format.js
      end

	end

	def show
	end

	def listpdf
		if (cookies[:regimen].present? || cookies[:category].present?  || cookies[:manyinputs].present? )
			@employee = @@pepe.result(distinct: true)
		else
			@employee = Employee.all
		end
			respond_to do |format|
				format.html
				format.pdf do 
					render :pdf         => "file_name",
					:layout=>  'pdf.html', 
					:page_size => 'A4',
					:dpi=>'72',
					title: 'Listado empleados', 
					:margin => {:top => 26, :bottom =>21 },
					:header => {
					:content => render_to_string(:template => 'pdf-component/header.pdf.erb')
					},
					:footer => {
					:content => render_to_string(:template => 'pdf-component/footer.pdf.erb')
					 }
				end
			end
	end

  def employee_params
    params.require(:employee).permit(:legajo, :name, :last_name, :cuil, :document_type, :document_number, :birthday, :marital_state, :avatar, :email, :tel_cel, :tel_home, :other_tel)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_print_dialog_list.html.erb
<div class="modal listModal" id="miModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button class="close" aria-hidden="true" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title"><i class="fa fa-print" aria-hidden="true"></i>
  Campos a imprimir </h4>
                        </div>


   <%= form_tag listpdf_home_path(@employee, format: :pdf, :html => {:class => "form_print_dialog"}, :method => "post"), :target => '_blank' do  %>


                        <div class="modal-body">
          
                         <ul class="list-group">
                            <li class="list-group-item">
                                  Apellido y Nombre
                                <div class="material-switch pull-right">
                                    <%= check_box_tag :name_and_lastname %>
                                    <label for="name_and_lastname" class="label-success"></label>
                                </div>
                            </li>

                             <li class="list-group-item">
                                    Legajo
                                    <div class="material-switch pull-right">
                                        <%= check_box_tag :legajo %>
                                        <label for="legajo" class="label-success"></label>
                                    </div>
                            </li>
                            <!-- Disabled -->
                            <li class="list-group-item">
                                <strike>Categoría</strike><small><mark>Temporalmente deshabilitado.</mark></small>
                                <div class="material-switch pull-right">
                                    <%= check_box_tag :categoria %>
                                    <label for="categoria" class="label-success"></label>
                                </div>
                            </li>
                            <li class="list-group-item">
                                <strike>Regimen</strike><small><mark>Temporalmente deshabilitado.</mark></small>
                                <div class="material-switch pull-right">
                                    <%= check_box_tag :regimen %>
                                    <label for="regimen" class="label-success"></label>
                                </div>
                            </li>
                            <!-- End Disabled -->
                             <li class="list-group-item">
                                D.N.I
                                <div class="material-switch pull-right">
                                    <%= check_box_tag :dni %>
                                    <label for="dni" class="label-success"></label>
                                </div>
                            </li>
                            <li class="list-group-item">
                                C.U.I.L
                                <div class="material-switch pull-right">
                                    <%= check_box_tag :cuil %>
                                    <label for="cuil" class="label-success"></label>
                                </div>
                            </li>
                            <li class="list-group-item">
                                Email
                                <div class="material-switch pull-right">
                                    <%= check_box_tag :email %>
                                    <label for="email" class="label-success"></label>
                                </div>
                            </li>
                         </ul>
                        </div>

                        <div class="modal-footer">
                    <button class="btn btn-default"  type="submit">Imprimir</button>
                   
                            <button class="btn btn-default" data-dismiss="modal">Cancelar</button>                           
                        </div>
                          <%end%>


                    </div>
                </div>
            </div>

app/views/home/_tableusers.html.erb
  <table class="table table-striped">
    <thead>
      <tr>
      <th class="text-xs-center">
        <i class="fa fa-user fa-lg"  aria-hidden="true"></i>
      </th>
      <th>Legajo</th>
      <th>Apellido y Nombre</th>
      <th class="text-xs-center">Categoria</th>
      <th> Regimen </th>
      <th>N° DNI</th>
      <!-- <th>Email</th> -->
      <th class="text-xs-center">Acciones</th>
      <th></th>
    </tr>
  </thead> 
  <tbody>
    <% @employee.each do |employee| %>
      <tr>
          <td class="text-xs-center">           
              <% unless employee.avatar.blank? %> <!-- Si no tiene imagen de avatar se toma una por defecto -->
              <%= image_tag(employee.avatar.url, alt:"avatar_principal", size:"40", :class=>'img-circle img-avatar')%>
              <% else %>
              <%=image_tag("users/default_avatar.png", alt:"avatar_principal", size:"40", :class=>'img-circle img-avatar')%>
              <% end %>  
          </td>
          
          <td class="text-xs-center">          
            <div class="small text-muted">
            <%= employee.legajo %>
            </div>
          </td>

          <td class="text-xs-center">
            <%= employee.last_name %>, <%= employee.name %>
          </td>

          <td class="text-xs-center">
            <div class="small text-muted">
              <% employee.labors.order(category: :desc).each do |labor| %>
                <%= labor.category %>
                <% break %>
              <% end %>
            </div>
          </td>

          <td class="text-xs-center">
            <div class="small text-muted">
              <% employee.labors.order(contracting_regime: :desc).each do |labor| %>
                <%= labor.contracting_regime %>
                <% break %>
              <% end %>
            </div>
          </td>

          <td class="text-xs-center">
            <div><%= employee.document_number %></div>
            <div class="small text-muted">
            CUIL: <%= employee.cuil %>              
            </div>
          </td>
           <td>
          <span>
            <%= link_to employee_path(employee), class: "btn btn-default print_list" do %>
                <i class="fa fa-eye fa-lg"></i>
            <% end %>   
          </span>             
        </td>
        <td>
        <div class="btn-table-users">

        <% academic_style = employee.academics.present? ? 'btn-default btn-xs btn-load tag-tooltip' : 'btn-default btn-xs btn-no-load tag-tooltip' %>

        <%= link_to '<i class="fa fa-graduation-cap" aria-hidden="true"></i>'.html_safe, academics_path(:id => employee.id), class:  academic_style.html_safe, :data => {:toggle=>"tooltip"}, 'data-original-title' => "Formación Académica" %>
    
        <% labor_style = employee.labors.present? ? 'btn-default btn-xs btn-load tag-tooltip' : 'btn-default btn-xs btn-no-load tag-tooltip' %>

        <%= link_to '<i class="fa fa-handshake-o" aria-hidden="true"></i>'.html_safe , labors_path(:id => employee.id), class:  labor_style.html_safe, :data => {:toggle=>"tooltip"}, 'data-original-title' => "Datos Laborales" %>
    
        <% clinical_style = employee.clinical ? 'btn-default btn-xs btn-load tag-tooltip' : 'btn-default btn-xs btn-no-load tag-tooltip' %>

        <%= link_to '<i class="fa fa-medkit" aria-hidden="true"></i>'.html_safe,  clinicals_path(:ids => employee.id), class:  clinical_style.html_safe, :data => {:toggle=>"tooltip"}, 'data-original-title' => "Datos Clínicos" %>

        <% family_style = employee.family_groups.present? ? 'btn-default btn-xs btn-load tag-tooltip' : 'btn-default btn-xs btn-no-load tag-tooltip' %>

        <%= link_to '<i class="fa fa-users" aria-hidden="true"></i>'.html_safe, family_groups_path(:employee_id => employee.id), class: family_style.html_safe, :data => {:toggle=>"tooltip"}, 'data-original-title' => "Grupo Familiar" %>

    



        </div>
        </td>

      </tr>
    <%end%>
  </tbody>
</table> 

app/views/home/index.html.erb
 <script>
  $(document).ready(function() {
    var dataTable = $('#users').dataTable();
    $("#searchbox").keyup(function() {
        dataTable.fnFilter(this.value);
     
    }); 


  
        $("#q_reset").click(function(){
        $("#q_legajo_cont").val('');
        $("#q_last_name_or_name_or_legajo_or_email_cont_any").val('');
        $("#select option:selected").val('');
        $("#q_labors_category_matches").val('');
        $("#q_labors_contracting_regime_matches").val('');

        $("#formsearch").submit();
    });
  });
</script>

  
 
<!-- Listad o de Empleados - Vista principal -->
 <%= render 'print_dialog_list' %> 
<div class="col-md-9"><!-- col empleados list -->
<div class="panel panel-default" >
  <div class="panel-heading">Empleados
      <div class="pull-right">
        <button class="btn btn-default print_list" data-toggle="modal" data-target="#miModal"> <i class="fa fa-print" aria-hidden="true"></i> </button>
      </div>
  </div>
 
      <div class="searchContenedor">

          <%= search_form_for @search,  :url => { :action => :index }, :html => { :id => "formsearch", :class=> "form-inline" }, remote: :true  do |f| %>


            <div class="row">
              <div class="col-md-12">
                  <div class="form-group">
                   
                    <%= f.search_field :last_name_or_name_or_legajo_or_email_cont_any, class: "form-control search_emp  input-sm", placeholder: "Legajo - Nombre - Apellido - DNI "  %>
               
                 </div>
              </div>
            </div>
            <br>
            <div class="row">
              <div class="col-md-3">
                  <div class="form-group">
                    <%= f.label :labors_category_matches, "Categoria" %>
                    <%= f.select :labors_category_matches,options_for_select([["",""], ["1", "1"], ["2", "2"], ["3","3"], ["4","4"], ["5","5"], ["6","6"], ["7","7"], ["8","8"], ["9","9"], ["10","10"], ["11","11"], ["12","12"], ["13","13"], ["14","14"], ["15","15"], ["16","16"], ["17","17"], ["18","18"], ["19","19"], ["20","20"], ["21","21"], ["22","22"], ["23","23"], ["24","24"]]), {},{class: "form-control  input-sm"}%>

                 </div>
               </div>


              <div class="col-md-4">
                <div class="form-class">
                    <%= f.label :labors_contracting_regime_matches, "Regimen" %>
                    <%= f.select :labors_contracting_regime_matches,  options_for_select([["",""], ["Planta Permanente", "Planta Permanente"], ["Planta Temporaria","Planta Temporaria"], ["Retiro Voluntario","Retiro Voluntario"], ["Otras Instituciones","Otras Instituciones"]]), {}, {class: "form-control  input-sm"}  %>
                </div>
              </div>  

              <div class="col-md-2">
                <div class="form-group">
                  <%= button_tag(type: 'submit',  class: "btn btn-default btn-sm") do %>
                  <i class="fa fa-search" aria-hidden="true"></i>
                  Buscar
                  <% end %>
                </div>
              </div>
              <div class="col-md-2">

                <div class="form-group">
                  <%= button_tag(type: 'submit', :name => nil, :id => :q_reset,  class: "btn btn-default btn-sm") do %>
                  Limpiar
                  <% end %>
                </div>
              </div>   
            </div>
            <br>



          <% end %>
        </div> <!-- Fin Search Contenedor -->
      <br>

  <div class="empleadostable">
        <%= render 'tableusers'%>
  </div>
  <div class="container pull-">
    <%= paginate @employee %>

  </div>


</div> <!-- Fin panel panel-default -->
</div> <!-- Fin empleados list - col-md-8 -->


<div class="col-md-3"><!-- col contratos a vencer -->
    <div class="panel panel-danger">
      <div class="panel-heading">
        Contratos a expirar 
        <span class="badge">
          <%= @count.present? ? @count : '' %>
        </span>
      </div>
        <%= render 'labors/unexpired_contracts', object: @labors %>
    </div>
    <br>
    <div class="panel panel-info"><!-- mayoria de edad en hijos -->
      <div class="panel-heading">Notificaciones</div>
        <%= render 'family_groups/full_age', object: @full_age %>
    </div>
</div><!-- /col contratos a vencer -->


<!-- Window minimize div -->
<script>
  $("#buttones").click(function(){
    if($(this).html() == "x"){
        $(this).html("<i class='fa fa-window-maximize' aria-hidden='true'></i>");
    }
    else{
        $(this).html("x");
    }
    $("#box").slideToggle();

  });
  $('#regimen').attr("disabled",true);
  $('#categoria').attr("disabled",true);

</script>

app/views/home/index.js.erb
    $(".empleadostable").empty();
    $(".empleadostable").append("<%= escape_javascript(render 'tableusers') %>");


 

app/views/home/listpdf.pdf.erb
 <div class="pdfList">
 <p class="titulo">Listado de empleados</p>
 	
 <table class="table table-bordered table-striped ">
    <thead>
      <tr>
      <% if params[:name_and_lastname]%>
        <th>Apellido y Nombre</th>
      <% end %>
      <% if params[:legajo]%>
        <th>Legajo</th>
      <%end%>
      <% if params[:categoria]%>
        <th>Cat.</th>
      <%end%>
      <% if params[:regimen]%>
        <th>Regimen</th>
      <%end%>
      <% if params[:dni]%>
        <th>D.N.I</th>
      <%end%>
      <% if params[:cuil]%>
        <th>C.U.I.L</th>
      <%end%>
      <% if params[:email]%>
        <th>Email</th>
        <%end%>
      </tr>
    </thead>
    <tbody>

<% @employee.each do |employee| %>
      <tr>
        <% if params[:name_and_lastname]%>
          <td>
            <%= employee.last_name %>, <%= employee.name %>
          </td>
        <%end%>
        <% if params[:legajo]%>
          <td>        
            <%= employee.legajo %>
          </td>
        <%end%>
         <% if params[:categoria]%>
          <td >
             <%= employee.category %>
          </td>
          <%end%>

   <% if params[:regimen]%>
          <td>
              <%= employee.regimen%>
          </td>
    <%end%>
 <% if params[:dni]%>
          <td>
            <%= employee.document_number %>
          </td>
          <%end%>
           <% if params[:cuil]%>
          <td>
          	<%= employee.cuil %>
          </td>
           
           <%end%>
            <% if params[:email]%>
            <td>
          	<%= employee.email%>
          </td>
          <%end%>


      </tr>
    <%end%>

    </tbody>
  </table>
 </div>